name: Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout documentation"
        uses: actions/checkout@v1

      - name: "Deploy documentation to Github Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/main/resources/api
